openapi: '3.0.2'
info:
  title: Heroes API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /heroes-statistics:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
  /hello:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                  payload:
                    type: object
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      parameters:
        - name: lang
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                  payload:
                    type: object
components:
  schemas:
    Statistics:
      type: object
      properties:
        charactersCount:
          type: number
        averageAge:
          type: number
        averageWeight:
          type: number
        genders: 
          type: object
          properties:
            female:
              type: number
            male:
              type: number
            other:
              type: number
        characters:
          type: array
          items:
            $ref: '#/components/schemas/Character'
      required:
        - charactersCount
        - averageAge
        - averageWeight
        - genders
        - characters
    Character:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        gender:
          type: string
        ability:
          type: string
        minimalDistance:
          type: number
        weight:
          type: number
        born:
          type: string
        inSpaceSince:
          type: string
        beerConsumption:
          type: number
        knowsTheAnswer:
          type: boolean