/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/heroes-statistics": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["Statistics"];
          };
        };
      };
    };
  };
  "/hello": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              hello?: string;
              payload?: { [key: string]: unknown };
            };
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          lang?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              hello?: string;
              payload?: { [key: string]: unknown };
            };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Statistics: {
      charactersCount: number;
      averageAge: number;
      averageWeight: number;
      genders: {
        female?: number;
        male?: number;
        other?: number;
      };
      characters: components["schemas"]["Character"][];
    };
    Character: {
      id?: number;
      name?: string;
      gender?: string;
      ability?: string;
      minimalDistance?: number;
      weight?: number;
      born?: string;
      inSpaceSince?: string;
      beerConsumption?: number;
      knowsTheAnswer?: boolean;
    };
  };
}

export interface operations {}

export interface external {}
